name: Maven CI

on:
  push:
    branches:
      - main
env:
  APP_NAME: github-actions
  APP_ENV: production
jobs:
  build:
    strategy:
      matrix:
        java: ['17', '21']
        os: [ubuntu-latest]
        include:
          - java: '17'
            environment: Production
          - java: '21'
            environment: Testing
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: display matrix info
        run: |
          echo "java: ${{matrix.java}}"
          echo "environment: ${{matrix.environment}}"
      - name: Display Environment
        run: |
          echo "appname: $APP_NAME"
          echo "appenvironment: $APP_ENV"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java}}
          distribution: 'temurin'
          cache: maven

      - name: Build and Test
        run: mvn clean package
        working-directory: github-actions-app

      - name: Upload artifacts
        if: matrix.java == '17'
        uses: actions/upload-artifact@v4
        with:
          name: github-actions-app
          path: github-actions-app/target/*.jar

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: Production
    env:
      JOB_NAME: deploy

    steps:
      - name: Downloading artifacts
        uses: actions/download-artifact@v4
        with:
          name: github-actions-app
          path: app
      - name: create deployment directory
        run: mkdir deployment
      - name: copy jar file from app to deployment
        run: cp -r app/ deployment/
      - name: display job name 
        run: 'echo "the job name: $JOB_NAME"'
      - name: githubsecret
        run: |
          echo "secret configuration"
          echo "secret value: ${{secrets.TEST_SECRET}}"
      - name: github value
        run: |
          echo "github variable configuration"
          echo "variable: ${{vars.DEPLOY_ENV}}"
      - name: github context 
        run: |
          echo "Branch: ${{github.ref}}"
          echo "Triggered by: ${{github.actor}}"
          echo "Repository: ${{github.repository}}"
          echo "commit: ${{github.sha}}"
          echo "workflow: ${{github.workflow}}"
          echo "Run Number: ${{github.run_number}}"
      - name: step level if condition
        if: github.ref == 'refs/heads/main'
        run: echo "running this from main brnach"
      - name: normally triggereing the step 
        run: echo "this normally execution"
      - name: Deploy success 
        if: success()
        run: echo "Deploy stage is success"
      - name: deploy failure
        if: failure()
        run: echo "deployment failed"
        
