name: Maven CI

on:
  push:
    branches:
      - main
env:
  APP_NAME: github-actions
  APP_ENV: production
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: environment display
        run: |
          echo "appname: $APP_NAME"
          echo "appenvironment: $APP_ENV"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test
        run: mvn clean package
        working-directory: github-actions-app

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: github-actions-app
          path: github-actions-app/target/*.jar

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      JOB_NAME: deploy

    steps:
      - name: Downloading artifacts
        uses: actions/download-artifact@v4
        with:
          name: github-actions-app
          path: app
      - name: create deployment directory
        run: mkdir deployment
      - name: copy jar file from app to deployment
        run: cp -r app/ deployment/
      - name: display job name 
        run: 'echo "the job name: $JOB_NAME"'
      - name: githubsecret
        run: |
          echo "secret configuration"
          echo "secret value: ${{secrets.TEST_SECRET}}"
      - name: github value
        run: |
          echo "github variable configuration"
          echo "variable: ${{vars.DEPLOY_ENV}}"
