name: Docker ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
jobs:
  runs-on: ubuntu-latest
  environment: Testing

  steps:
    - name: checkout Code
      uses: actions/checkout@v4
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::283609055440:role/GitHubActions-Testing-Deploy
        aws-region: us-east-1
      
    - name: loginto aws ecr
      uses: aws-actions/amazon-ecr-login@v2